/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReadingStatus = IDL.Variant({
  'reading' : IDL.Null,
  'read' : IDL.Null,
  'wantToRead' : IDL.Null,
});
export const Time = IDL.Int;
export const Book = IDL.Record({
  'status' : ReadingStatus,
  'title' : IDL.Text,
  'author' : IDL.Text,
  'genre' : IDL.Text,
  'notes' : IDL.Text,
  'rating' : IDL.Nat8,
  'coverUrl' : IDL.Opt(IDL.Text),
  'dateAdded' : Time,
});
export const BookId = IDL.Nat;

export const idlService = IDL.Service({
  'addBook' : IDL.Func([Book], [BookId], []),
  'deleteBook' : IDL.Func([BookId], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(IDL.Tuple(BookId, Book))], ['query']),
  'getBook' : IDL.Func([BookId], [Book], ['query']),
  'updateBook' : IDL.Func([BookId, Book], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReadingStatus = IDL.Variant({
    'reading' : IDL.Null,
    'read' : IDL.Null,
    'wantToRead' : IDL.Null,
  });
  const Time = IDL.Int;
  const Book = IDL.Record({
    'status' : ReadingStatus,
    'title' : IDL.Text,
    'author' : IDL.Text,
    'genre' : IDL.Text,
    'notes' : IDL.Text,
    'rating' : IDL.Nat8,
    'coverUrl' : IDL.Opt(IDL.Text),
    'dateAdded' : Time,
  });
  const BookId = IDL.Nat;
  
  return IDL.Service({
    'addBook' : IDL.Func([Book], [BookId], []),
    'deleteBook' : IDL.Func([BookId], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(IDL.Tuple(BookId, Book))], ['query']),
    'getBook' : IDL.Func([BookId], [Book], ['query']),
    'updateBook' : IDL.Func([BookId, Book], [], []),
  });
};

export const init = ({ IDL }) => { return []; };