/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'status' : ReadingStatus,
  'title' : string,
  'author' : string,
  'genre' : string,
  'notes' : string,
  'rating' : number,
  'coverUrl' : [] | [string],
  'dateAdded' : Time,
}
export type BookId = bigint;
export type ReadingStatus = { 'reading' : null } |
  { 'read' : null } |
  { 'wantToRead' : null };
export type Time = bigint;
export interface _SERVICE {
  'addBook' : ActorMethod<[Book], BookId>,
  'deleteBook' : ActorMethod<[BookId], undefined>,
  'getAllBooks' : ActorMethod<[], Array<[BookId, Book]>>,
  'getBook' : ActorMethod<[BookId], Book>,
  'updateBook' : ActorMethod<[BookId, Book], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];