/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Book {
    status: ReadingStatus;
    title: string;
    author: string;
    genre: string;
    notes: string;
    rating: number;
    coverUrl?: string;
    dateAdded: Time;
}
export type BookId = bigint;
export type Time = bigint;
export enum ReadingStatus {
    reading = "reading",
    read = "read",
    wantToRead = "wantToRead"
}
export interface backendInterface {
    addBook(book: Book): Promise<BookId>;
    deleteBook(id: BookId): Promise<void>;
    getAllBooks(): Promise<Array<[BookId, Book]>>;
    getBook(id: BookId): Promise<Book>;
    updateBook(id: BookId, book: Book): Promise<void>;
}
import type { Book as _Book, BookId as _BookId, ReadingStatus as _ReadingStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBook(arg0: Book): Promise<BookId> {
        if (this.processError) {
            try {
                const result = await this.actor.addBook(to_candid_Book_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBook(to_candid_Book_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBook(arg0: BookId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBook(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBook(arg0);
            return result;
        }
    }
    async getAllBooks(): Promise<Array<[BookId, Book]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBooks();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBooks();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBook(arg0: BookId): Promise<Book> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return from_candid_Book_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return from_candid_Book_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBook(arg0: BookId, arg1: Book): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBook(arg0, to_candid_Book_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBook(arg0, to_candid_Book_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Book_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Book): Book {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ReadingStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReadingStatus): ReadingStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ReadingStatus;
    title: string;
    author: string;
    genre: string;
    notes: string;
    rating: number;
    coverUrl: [] | [string];
    dateAdded: _Time;
}): {
    status: ReadingStatus;
    title: string;
    author: string;
    genre: string;
    notes: string;
    rating: number;
    coverUrl?: string;
    dateAdded: Time;
} {
    return {
        status: from_candid_ReadingStatus_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        author: value.author,
        genre: value.genre,
        notes: value.notes,
        rating: value.rating,
        coverUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.coverUrl)),
        dateAdded: value.dateAdded
    };
}
function from_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_BookId, _Book]): [BookId, Book] {
    return [
        value[0],
        from_candid_Book_n7(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reading: null;
} | {
    read: null;
} | {
    wantToRead: null;
}): ReadingStatus {
    return "reading" in value ? ReadingStatus.reading : "read" in value ? ReadingStatus.read : "wantToRead" in value ? ReadingStatus.wantToRead : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_BookId, _Book]>): Array<[BookId, Book]> {
    return value.map((x)=>from_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Book_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Book): _Book {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ReadingStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReadingStatus): _ReadingStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ReadingStatus;
    title: string;
    author: string;
    genre: string;
    notes: string;
    rating: number;
    coverUrl?: string;
    dateAdded: Time;
}): {
    status: _ReadingStatus;
    title: string;
    author: string;
    genre: string;
    notes: string;
    rating: number;
    coverUrl: [] | [string];
    dateAdded: _Time;
} {
    return {
        status: to_candid_ReadingStatus_n3(_uploadFile, _downloadFile, value.status),
        title: value.title,
        author: value.author,
        genre: value.genre,
        notes: value.notes,
        rating: value.rating,
        coverUrl: value.coverUrl ? candid_some(value.coverUrl) : candid_none(),
        dateAdded: value.dateAdded
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReadingStatus): {
    reading: null;
} | {
    read: null;
} | {
    wantToRead: null;
} {
    return value == ReadingStatus.reading ? {
        reading: null
    } : value == ReadingStatus.read ? {
        read: null
    } : value == ReadingStatus.wantToRead ? {
        wantToRead: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
